<?php

/*
 * Requiring Module Files
 */

/*
 * Location Custom Posts Metas Keys
 */


define('CAAG_HQ_RENTAL_LOCATION_ID_META', 'caag_hq_rental_location_id_meta');
define('CAAG_HQ_RENTAL_LOCATION_NAME_META', 'caag_hq_rental_location_name_meta');
define('CAAG_HQ_RENTAL_LOCATION_BRAND_ID_META', 'caag_hq_rental_location_brand_id_meta');
define('CAAG_HQ_RENTAL_LOCATION_IS_AIRPORT_META', 'caag_hq_rental_location_is_airport_meta');
define('CAAG_HQ_RENTAL_LOCATION_IS_OFFICE_META', 'caag_hq_rental_location_is_office_meta');
define('CAAG_HQ_RENTAL_LOCATION_ACTIVE_META', 'caag_hq_rental_location_active_meta');
define('CAAG_HQ_RENTAL_LOCATION_WAS_UPLOAD_IT_META','caag_hq_rental_location_was_upload_it_meta');

/*
 * Rates Custom Posts Metas keys
 */
define('CAAG_HQ_RENTAL_RATE_ID_META', 'caag_hq_rental_rate_id_meta');
define('CAAG_HQ_RENTAL_RATE_SEASON_ID_META', 'caag_hq_rental_rate_season_id_meta');
define('CAAG_HQ_RENTAL_RATE_VEHICLE_CLASS_ID_META', 'caag_hq_rental_rate_vehicle_class_id_meta');
define('CAAG_HQ_RENTAL_RATE_BASE_RATE_META','caag_hq_rental_rate_base_rate_meta');
define('CAAG_HQ_RENTAL_RATE_HOURLY_RATE_META','caag_hq_rental_rate_hourly_rate_meta');
define('CAAG_HQ_RENTAL_RATE_DAILY_RATE_META','caag_hq_rental_rate_daily_rate_meta');
define('CAAG_HQ_RENTAL_RATE_WEEKLY_RATE_META','caag_hq_rental_rate_weekly_rate_meta');
define('CAAG_HQ_RENTAL_RATE_MONTHLY_RATE_META','caag_hq_rental_rate_monthly_rate_meta');

/*
 * Vehicle Classes Custom Metas keys
 */
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_ID_META', 'caag_hq_rental_vehicle_class_id_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_BRAND_ID_META', 'caag_hq_rental_vehicle_class_brand_id_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_NAME_META', 'caag_hq_rental_vehicle_class_name_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_LABEL_FOR_WEBSITE_EN_META', 'caag_hq_rental_vehicle_class_label_for_website_en_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_LABEL_FOR_WEBSITE_NL_META', 'caag_hq_rental_vehicle_class_label_for_website_nl_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_LABEL_FOR_WEBSITE_DE_META', 'caag_hq_rental_vehicle_class_label_for_website_de_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_SHORT_DESCRIPTION_FOR_WEBSITE_EN_META', 'caag_hq_rental_vehicle_class_short_description_for_website_en_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_SHORT_DESCRIPTION_FOR_WEBSITE_NL_META', 'caag_hq_rental_vehicle_class_short_description_for_website_nl_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_SHORT_DESCRIPTION_FOR_WEBSITE_DE_META', 'caag_hq_rental_vehicle_class_short_description_for_website_de_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_DESCRIPTION_FOR_WEBSITE_EN_META', 'caag_hq_rental_vehicle_class_description_for_website_en_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_DESCRIPTION_FOR_WEBSITE_NL_META', 'caag_hq_rental_vehicle_class_description_for_website_nl_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_DESCRIPTION_FOR_WEBSITE_DE_META', 'caag_hq_rental_vehicle_class_description_for_website_de_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_IMAGE_LINK_META', 'caag_hq_rental_vehicle_class_image_link_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_IMAGE_EXTENSION_META', 'caag_hq_rental_vehicle_class_image_extension_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_ACTIVE_RATE_ID_META', 'caag_hq_rental_vehicle_class_active_rate_id_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_ACTIVE_RATE_SEASON_ID_META', 'caag_hq_rental_vehicle_class_active_season_id_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_ACTIVE_RATE_BASE_RATE_META', 'caag_hq_rental_vehicle_class_active_rate_base_rate_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_ACTIVE_RATE_HOURLY_RATE_META', 'caag_hq_rental_vehicle_class_active_rate_hourly_rate_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_ACTIVE_RATE_DAILY_RATE_META', 'caag_hq_rental_vehicle_class_active_rate_daily_rate_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_ACTIVE_RATE_WEEKLY_RATE_META', 'caag_hq_rental_vehicle_class_active_rate_weekly_rate_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_ACTIVE_RATE_MONTHLY_RATE_META', 'caag_hq_rental_vehicle_class_active_rate_monthly_rate_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_ACTIVE_RATE_BASE_RATE_PLUS_TAX_META', 'caag_hq_rental_vehicle_class_active_rate_base_rate_plus_tax_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_ACTIVE_RATE_HOURLY_RATE_PLUS_TAX_META', 'caag_hq_rental_vehicle_class_active_rate_hourly_rate_plus_tax_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_ACTIVE_RATE_DAILY_RATE_PLUS_TAX_META', 'caag_hq_rental_vehicle_class_active_rate_daily_rate_plus_tax_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_ACTIVE_RATE_WEEKLY_RATE_PLUS_TAX_META', 'caag_hq_rental_vehicle_class_active_rate_weekly_rate_plus_tax_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_ACTIVE_RATE_MONTHLY_RATE_PLUS_TAX_META', 'caag_hq_rental_vehicle_class_active_rate_monthly_rate_plus_tax_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_ACTIVE_RATE_DECREASING_RATES_BASED_ON_INTERVALS_META', 'caag_hq_rental_vehicle_class_active_rate_decreasing_rates_based_on_intervals_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_CAAG_ID_ON_WOOCOMMERCE_PRODUCT_META', 'caag_hq_rental_vehicle_class_caag_id_on_woocommerce_product_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_CAAG_BRAND_ID_ON_WOOCOMMERCE_PRODUCT_META', 'caag_hq_rental_vehicle_class_caag_brand_id_on_woocommerce_product_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_CUSTOM_FIELD_F214_META', 'caag_hq_rental_vehicle_class_custom_field_214_product_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_CUSTOM_FIELD_F215_META', 'caag_hq_rental_vehicle_class_custom_field_215_product_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_CUSTOM_FIELD_F222_META', 'caag_hq_rental_vehicle_class_custom_field_222_product_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_CUSTOM_FIELD_F226_META', 'caag_hq_rental_vehicle_class_custom_field_226_product_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_CUSTOM_FIELD_F227_META', 'caag_hq_rental_vehicle_class_custom_field_227_product_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_CUSTOM_FIELD_F235_META', 'caag_hq_rental_vehicle_class_custom_field_235_product_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_CUSTOM_FIELD_F217_META', 'caag_hq_rental_vehicle_class_custom_field_217_product_meta');

/*
 * Vehicle Classes Images
 */
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_IMAGES_ID_META', 'caag_hq_rental_vehicle_class_image_id_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_IMAGES_CAAG_VEHICLE_CLASS_CAAG_ID_META', 'caag_hq_rental_vehicle_class_image_vehicle_class_caag_id_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_IMAGES_FILENAME_META', 'caag_hq_rental_vehicle_class_image_filename_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_IMAGES_EXTENSION_META', 'caag_hq_rental_vehicle_class_image_extension_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_IMAGES_MIME_META', 'caag_hq_rental_vehicle_class_image_mime_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_IMAGES_PUBLIC_LINK_META', 'caag_hq_rental_vehicle_class_image_public_link_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_IMAGES_VEHICLE_CLASS_CUSTOM_POST_ID_META', 'caag_hq_rental_vehicle_class_image_custom_post_id_meta');

/*
 * Decreasing Rates
 */
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_DECREASING_RATE_ORDER_META', 'caag_hq_rental_vehicle_class_decreasing_rate_order_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_DECREASING_RATE_PRICE_META', 'caag_hq_rental_vehicle_class_decreasing_price_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_DECREASING_RATE_START_INTERVAL_META', 'caag_hq_rental_vehicle_class_decreasing_rate_start_interval_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_DECREASING_RATE_END_INTERVAL_META', 'caag_hq_rental_vehicle_class_decreasing_rate_end_interval_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_DECREASING_RATE_VEHICLE_CLASS_CAAG_ID_META', 'caag_hq_rental_vehicle_class_decreasing_rate_vehicle_class_caag_id_meta');
define('CAAG_HQ_RENTAL_VEHICLE_CLASS_DECREASING_RATE_VEHICLE_CLASS_CUSTOM_POST_ID_META', 'caag_hq_rental_vehicle_class_decreasing_rate_vehicle_class_custom_post_id_meta');
/*
 * Features Custom Metas Keys
 */
define('CAAG_HQ_RENTAL_FEATURES_ID_META', 'caag_hq_rental_features_id_meta');
define('CAAG_HQ_RENTAL_FEATURES_VEHICLE_CLASS_ID_META', 'caag_hq_rental_features_vehicle_class_id_meta');
define('CAAG_HQ_RENTAL_FEATURES_VEHICLE_CLASS_POST_ID_META', 'caag_hq_rental_features_vehicle_class_post_id_meta');
define('CAAG_HQ_RENTAL_FEATURES_LABEL_META', 'caag_hq_rental_features_label_meta');
define('CAAG_HQ_RENTAL_FEATURES_LABEL_FOR_WEBSITE_META', 'caag_hq_rental_features_label_for_website_meta');
define('CAAG_HQ_RENTAL_FEATURES_ICON_META', 'caag_hq_rental_features_icon_meta');

/*
 * Additional Charges Metas Keys
 */
define('CAAG_HQ_RENTAL_ADDITIONAL_CHARGES_ID_META', 'caag_hq_rental_additional_charges_id_meta');
define('CAAG_HQ_RENTAL_ADDITIONAL_CHARGES_NAME_META', 'caag_hq_rental_additional_charges_name_meta');
define('CAAG_HQ_RENTAL_ADDITIONAL_CHARGES_CHARGE_TYPE_META', 'caag_hq_rental_additional_charges_charge_type_meta');
define('CAAG_HQ_RENTAL_ADDITIONAL_CHARGES_SELECTION_TYPE_META', 'caag_hq_rental_additional_charges_selection_type_meta');
define('CAAG_HQ_RENTAL_ADDITIONAL_CHARGES_DESCRIPTION_EN_META', 'caag_hq_rental_additional_charges_description_en_meta');
define('CAAG_HQ_RENTAL_ADDITIONAL_CHARGES_DESCRIPTION_NL_META', 'caag_hq_rental_additional_charges_description_nl_meta');
define('CAAG_HQ_RENTAL_ADDITIONAL_CHARGES_DESCRIPTION_ES_META', 'caag_hq_rental_additional_charges_description_es_meta');
define('CAAG_HQ_RENTAL_ADDITIONAL_CHARGES_DESCRIPTION_PT_META', 'caag_hq_rental_additional_charges_description_pt_meta');
define('CAAG_HQ_RENTAL_ADDITIONAL_CHARGES_DESCRIPTION_DE_META', 'caag_hq_rental_additional_charges_description_de_meta');
define('CAAG_HQ_RENTAL_ADDITIONAL_CHARGES_ICON_META', 'caag_hq_rental_additional_charges_icon_meta');
define('CAAG_HQ_RENTAL_ADDITIONAL_CHARGES_LABEL_FOR_WEBSITE_EN_META', 'caag_hq_rental_additional_charges_label_for_website_en_meta');
define('CAAG_HQ_RENTAL_ADDITIONAL_CHARGES_LABEL_FOR_WEBSITE_NL_META', 'caag_hq_rental_additional_charges_label_for_website_nl_meta');
define('CAAG_HQ_RENTAL_ADDITIONAL_CHARGES_LABEL_FOR_WEBSITE_ES_META', 'caag_hq_rental_additional_charges_label_for_website_es_meta');
define('CAAG_HQ_RENTAL_ADDITIONAL_CHARGES_LABEL_FOR_WEBSITE_PT_META', 'caag_hq_rental_additional_charges_label_for_website_pt_meta');
define('CAAG_HQ_RENTAL_ADDITIONAL_CHARGES_LABEL_FOR_WEBSITE_DE_META', 'caag_hq_rental_additional_charges_label_for_website_de_meta');
define('CAAG_HQ_RENTAL_ADDITIONAL_CHARGES_SHORT_DESCRIPTION_FOR_WEBSITE_EN_META', 'caag_hq_rental_additional_charges_short_description_for_website_en_meta');
define('CAAG_HQ_RENTAL_ADDITIONAL_CHARGES_SHORT_DESCRIPTION_FOR_WEBSITE_NL_META', 'caag_hq_rental_additional_charges_short_description_for_website_nl_meta');
define('CAAG_HQ_RENTAL_ADDITIONAL_CHARGES_SHORT_DESCRIPTION_FOR_WEBSITE_ES_META', 'caag_hq_rental_additional_charges_short_description_for_website_es_meta');
define('CAAG_HQ_RENTAL_ADDITIONAL_CHARGES_SHORT_DESCRIPTION_FOR_WEBSITE_PT_META', 'caag_hq_rental_additional_charges_short_description_for_website_pt_meta');
define('CAAG_HQ_RENTAL_ADDITIONAL_CHARGES_SHORT_DESCRIPTION_FOR_WEBSITE_DE_META', 'caag_hq_rental_additional_charges_short_description_for_website_de_meta');


/*
 * Seasons Custom Metas keys
 */
define('CAAG_HQ_RENTAL_SEASON_ID_META', 'caag_hq_rental_season_id_meta');
define('CAAG_HQ_RENTAL_SEASON_BRAND_ID_META', 'caag_hq_rental_season_brand_id_meta');
define('CAAG_HQ_RENTAL_SEASON_NAME_META', 'caag_hq_rental_season_name_meta');
define('CAAG_HQ_RENTAL_SEASON_DATE_START_META', 'caag_hq_rental_season_date_start_meta');
define('CAAG_HQ_RENTAL_SEASON_DATE_END_META', 'caag_hq_rental_season_date_end_meta');
define('CAAG_HQ_RENTAL_SEASON_MINIMAL_RENTAL_PERIOD_META', 'caag_hq_rental_season_minimal_rental_period_meta');

require_once('utils.php');
require_once('locations.php');
require_once('rates.php');
require_once('features.php');
require_once('seasons.php');
require_once('additional-charges.php');
require_once('vehicle-class-images.php');
require_once('vehicle-class-decreasing-rates.php');
require_once('vehicles-classes.php');



